# Generated by Django 5.2.11 on 2026-02-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchevent_added_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livematch',
            old_name='league',
            new_name='league_name',
        ),
    ]
