# Generated by Django 5.2.11 on 2026-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_rename_league_livematch_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='country_name',
            field=models.CharField(default='Nieznany', max_length=100),
        ),
    ]
