# Generated by Django 5.2.11 on 2026-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_livematch_league_name_league_country_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchlineup',
            unique_together={('match', 'player_name', 'is_home_team')},
        ),
        migrations.AddField(
            model_name='matchevent',
            name='assist2_player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='confirmed',
            field=models.BooleanField(blank=True, help_text='VAR: czy decyzja potwierdzona', null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='incident_class',
            field=models.CharField(blank=True, help_text='np. regular, ownGoal, penalty, missedPenalty, yellow, yellowRed, red', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='injury',
            field=models.BooleanField(default=False, help_text='Czy zmiana spowodowana kontuzją'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Czy marker period oznacza mecz live'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='length',
            field=models.IntegerField(blank=True, help_text='Doliczony czas (minuty)', null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='reason',
            field=models.CharField(blank=True, help_text='Powód kartki', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='rescinded',
            field=models.BooleanField(default=False, help_text='Kartka anulowana przez VAR'),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='avg_rating',
            field=models.CharField(blank=True, help_text='Średnia ocena gracza z API', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchlineup',
            name='player_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='text',
            field=models.CharField(blank=True, help_text='np. HT, FT', max_length=20, null=True),
        ),
    ]
