# Generated by Django 5.2.11 on 2026-02-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_missingplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='stats_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
