# Generated by Django 5.2.11 on 2026-02-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_livematch_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID meczu z RapidAPI', unique=True)),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Dokładna data i czas rozpoczęcia (z startTimestamp)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_home_matches', to='matches.team')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_matches', to='matches.league')),
            ],
        ),
    ]
