# Generated by Django 5.2.11 on 2026-03-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_rename_preffered_foot_player_preferred_foot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='matches.livematch')),
            ],
            options={
                'unique_together': {('session_key', 'match')},
            },
        ),
    ]
