# Generated by Django 5.2.11 on 2026-03-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_alter_league_id_alter_livematch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_drawn', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_difference', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.team')),
            ],
        ),
    ]
