# Generated by Django 5.2.11 on 2026-04-20 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_livematch_is_top'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='matches.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulubiona drużyna',
                'verbose_name_plural': 'Ulubione drużyny',
                'unique_together': {('user', 'team')},
            },
        ),
    ]
