# Generated by Django 5.2.11 on 2026-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_favoriteteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
