# Generated by Django 5.2.11 on 2026-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_favoriteteam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
