# Generated by Django 5.2.11 on 2026-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_matchsubscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='livematch',
            name='last_notified_score',
            field=models.CharField(default='0:0', help_text="Wynik w formacie 'X:Y' przy ostatnim wysłanym Push o bramce", max_length=10),
        ),
        migrations.AddField(
            model_name='livematch',
            name='notified_event_ids',
            field=models.JSONField(blank=True, default=list, help_text='ID incydentów (z API) o których już wysłano Push Notification'),
        ),
    ]
