# Generated by Django 5.2.11 on 2026-04-20 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_add_push_tracking_and_subscription_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsubscription',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Zalogowany użytkownik (jeśli kliknął dzwoneczek będąc zalogowany)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
