
services:
  # 1. Twoja aplikacja Django
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 2. Baza Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 3. Twój robot do zadań w tle (Celery Worker)
  celery:
    build: .
    command: celery -A my_football_app worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # 4. Celery Beat
  celery-beat:
    build: .
    command: celery -A my_football_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: varify_db
      MYSQL_ROOT_PASSWORD: supertajnehaslo
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: