"""
Django settings for my_football_app project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sentry_sdk
from celery.schedules import crontab
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w#0c&!#4_gib+4(u!55*o%977%k-r_gbz$w-%9&@4t6)-j%i_$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['13.62.58.123', 'localhost', '127.0.0.1']

sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN", "https://57fe3a4f7a85f4c31ec62748e24ee3a7@o4511019727388672.ingest.de.sentry.io/4511019742003280"),
    send_default_pii=True,
    traces_sample_rate=1.0,
    profiles_sample_rate=1.0,
)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'matches',
    'rest_framework'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'my_football_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_football_app.wsgi.application'
ASGI_APPLICATION = 'my_football_app.asgi.application'

# Silence W042: use BigAutoField as the default primary key type for all models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Mówimy Django, jak nazywa się nasz adres logowania
LOGIN_URL = 'login'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'varify_db',             # Zgadza się z docker-compose
        'USER': 'root',                  # Domyślny użytkownik
        'PASSWORD': 'supertajnehaslo',   # Zgadza się z docker-compose
        'HOST': 'db',                    # Magia Dockera! Szukamy kontenera o nazwie "db"
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==========================================
# CELERY & REDIS SETTINGS
# ==========================================
# Gdzie Celery ma szukać nowych zadań (nasz lokalny Redis)
CELERY_BROKER_URL = 'redis://redis:6379/0'
# Gdzie Celery ma zapisywać wyniki zakończonych zadań
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
# Bezpieczeństwo - format danych do komunikacji to JSON
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'Europe/Warsaw'

# ==========================================
# CELERY BEAT (Harmonogram zadań)
# ==========================================
CELERY_BEAT_SCHEDULE = {
    'update-live-matches-every-30-seconds': {
        'task': 'matches.tasks.sync_live_matches',
        'schedule': 30.0, # Wykonuj co 30 sekund
    },
    'fetch-upcoming-matches': {
        'task': 'matches.tasks.fetch_upcoming_matches',
        'schedule': crontab(hour=11, minute=00), # Wykonuj o 
    },
    'fetch-top-leagues-standings': {
        'task': 'matches.tasks.fetch_top_leagues_standings_task',
        'schedule': crontab(hour=13, minute=19), # Codziennie o zadanej godzinie (według czasu lokalnego polskiego zachowanego w bazie)
    },
}


CACHES = {  
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("redis", 6379)],
        },
    },
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[%(levelname)s] %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        'matches': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

REST_FRAMEWORK = {
    # 1. Konfiguracja Throttlingu
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # Dla niezalogowanych (anonimowych)
        'rest_framework.throttling.UserRateThrottle'  # Dla zalogowanych użytkowników
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',  # Niezalogowany może wysłać max 30 zapytań na minutę
        'user': '20/minute',  # Zalogowany ma większy limit
    },
    # 2. Konfiguracja Pagination (stronicowania)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20 # Zwraca maksymalnie 20 elementów na jedno zapytanie
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # "https://twoja-domena.com",
]